Repository ILLUZORR/Europa-Plus, pull requests merged in 2025-10, with the labels that each got.

#31 [Fix] Tweaks and fixes in PDA coordinates.
  Resources/Prototypes/Entities/Objects/Devices/pda.yml
  Resources/Prototypes/_Goobstation/Entities/Objects/Devices/pda.yml
Labels: S: Неотсортированный, Изменения: Нет C#

#34 [Fix] RSI license validation fix
  .github/workflows/validate-rsis.yml
  Tools/Schemas/mapfile.yml
  Tools/Schemas/mapfile_requirements.txt
  Tools/Schemas/mapfile_validators.py
  Tools/Schemas/rga.yml
  Tools/Schemas/rga_requirements.txt
  Tools/Schemas/rga_validators.py
  Tools/Schemas/rsi.json
  Tools/Schemas/validate_rsis.py
Labels: S: Неотсортированный, Изменения: Нет C#

#37 [Fix] TTS on radio now works
  Content.Server/Radio/EntitySystems/HeadsetSystem.cs
Labels: S: Неотсортированный

#36 [MAPS]maps-update-1
  Resources/Maps/_Europa/aspid.yml
  Resources/Maps/_Europa/rook.yml
  Resources/Maps/_Goobstation/bagel.yml
  Resources/Maps/_Goobstation/loop.yml
  Resources/Prototypes/Maps/aspid.yml
  Resources/Prototypes/Maps/rook.yml
Labels: Изменения: Карты, Изменения: Нет C#

#38 [Bounty] Cryo Chemical Changes
  Resources/Locale/en-US/_europa/reagents/meta/medicine.ftl
  Resources/Locale/ru-RU/_europa/reagents/meta/medicine.ftl
  Resources/Prototypes/Reagents/medicine.yml
  Resources/Prototypes/Recipes/Reactions/medicine.yml
  Resources/Prototypes/_Europa/Reagents/medicine.yml
  Resources/Prototypes/_Europa/Recipes/Reactions/medicine.yml
Labels: Изменения: Локализация, Изменения: Нет C#

#43 [Feature] Custom Ghost
  Resources/Prototypes/_Europa/Ghosts/custom_ghosts.yml
  Resources/Textures/_Europa/Ghosts/ZnAkI.rsi/animated.png
  Resources/Textures/_Europa/Ghosts/ZnAkI.rsi/meta.json
Labels: S: Неотсортированный, Изменения: Спрайты, Изменения: Нет C#
